#!/bin/bash

#get OpsgenieEdgeConnector32.exe and oecService32.exe from s3
mkdir /oec
cp $OEC_SCRIPTS_REPO/release/oec-builder/executables/OpsgenieEdgeConnector32.exe /oec
cp $OEC_SCRIPTS_REPO/release/oec-builder/executables/oecService32.exe /oec

cp -R $INPUT/oecService.json.example /oec && \
cp -R $OEC_SCRIPTS_REPO/$INTEGRATION/. /oec && \

INTEGRATION_PATH=$(echo "$INTEGRATION" | awk '{print tolower($0)}')

#########incoming part##########
INCOMING_PATH=/oec/${INTEGRATION_PATH}
if [ -d "$INCOMING_PATH" ]; then
  go get -u github.com/alexcesaro/log && \
  cd /oec/${INTEGRATION_PATH} && \
  GOOS=windows GOARCH=386 go build -o send2opsgenie send2opsgenie.go
fi
################################

cd ~ && \
mkdir -p $OUTPUT/oec-packages-$OEC_VERSION/${INTEGRATION_PATH} && \

zip -r ${INTEGRATION_PATH}-$OEC_VERSION-win-386.zip /oec && \
cp -R ${INTEGRATION_PATH}* $OUTPUT/oec-packages-$OEC_VERSION/${INTEGRATION_PATH}/