#!/bin/bash

#get OpsgenieEdgeConnector32.exe and oecService32.exe from s3
mkdir /oec
cp $OEC_SCRIPTS_REPO/release/oec-builder/executables/OpsgenieEdgeConnector32.exe /oec
cp $OEC_SCRIPTS_REPO/release/oec-builder/executables/oecService32.exe /oec

cp -R $INPUT/oecService.json.example /oec && \
cp -R $OEC_SCRIPTS_REPO/$INTEGRATION/. /oec && \

#########incoming part##########
go get -u github.com/alexcesaro/log && \
cd /oec/${INTEGRATION,,} && \
GOOS=windows GOARCH=386 go build -o send2opsgenie send2opsgenie.go && \
################################

cd ~ && \
mkdir -p $OUTPUT/oec-packages-$OEC_VERSION/${INTEGRATION,,} && \

zip -r ${INTEGRATION,,}-$OEC_VERSION-win-386.zip /oec && \
cp -R ${INTEGRATION,,}* $OUTPUT/oec-packages-$OEC_VERSION/${INTEGRATION,,}/