#!/bin/bash
if [ ! -d "/var/log/opsgenie" ]; then
    mkdir /var/log/opsgenie
fi

if [ ! -d "/home/opsgenie" ]; then
    mkdir /home/opsgenie
fi

if [  -z $(getent passwd opsgenie) ]; then
    groupadd opsgenie -r
    useradd -g opsgenie opsgenie -r -d /home/opsgenie
fi
