#!/bin/bash

mkdir /oec
s3URL=https://og-release-cicd-public-oregon.s3-us-west-2.amazonaws.com/purpose%3Dpublic/project%3Doec-builder/env%3Dprod/branch%3D${BRANCH}/module%3Doec-builder/version%3D${OEC_VERSION}/oec-win64-${OEC_VERSION}.zip
curl ${s3URL} --output ./oec.zip --silent --show-error --create-dirs
unzip ./oec.zip -d /oec

cp -R $INPUT/oecService.json.example /oec && \
cp -R $OEC_SCRIPTS_REPO/$INTEGRATION/. /oec && \

INTEGRATION_PATH=$(echo "$INTEGRATION" | awk '{print tolower($0)}')

#########incoming part##########
INCOMING_PATH=/oec/${INTEGRATION_PATH}
if [ -d "$INCOMING_PATH" ]; then
  go get -u github.com/alexcesaro/log && \
  cd /oec/${INTEGRATION_PATH} && \
  GOOS=windows GOARCH=amd64 go build -o send2opsgenie send2opsgenie.go
fi
################################

cd ~ && \
mkdir -p $OUTPUT/oec-packages-$OEC_VERSION/${INTEGRATION_PATH} && \

zip -r ${INTEGRATION_PATH}-$OEC_VERSION-win-amd64.zip /oec  && \
cp -R ${INTEGRATION_PATH}* $OUTPUT/oec-packages-$OEC_VERSION/${INTEGRATION_PATH}/