#!/bin/bash

#need to get executables from s3 and put under oec-deb
mkdir -p /oec-deb/usr/local/bin
cp $OEC_SCRIPTS_REPO/release/oec-builder/executables/OpsgenieEdgeConnector /oec-deb/usr/local/bin

cp -R $INPUT/. /oec-deb && \
mkdir -p /oec-deb/home/opsgenie/oec/ && \
cp -R $OEC_SCRIPTS_REPO/$INTEGRATION/. /oec-deb/home/opsgenie/oec && \

####incoming part#######
go get -u github.com/alexcesaro/log && \
cd /oec-deb/home/opsgenie/oec/${INTEGRATION,,} && \
GOOS=linux GOARCH=amd64 go build -o send2opsgenie send2opsgenie.go && \
########################

sed -i "s|<path_of_script>|/home/opsgenie/oec/scripts/actionExecutor.py|" /oec-deb/home/opsgenie/oec/conf/config.json
sed -i "s|<path_of_output_file_of_script>|/home/opsgenie/oec/output/output.txt|" /oec-deb/home/opsgenie/oec/conf/config.json
sed -i "s/<local | git>/local/g" /oec-deb/home/opsgenie/oec/conf/config.json

sed -i "s/%VERSION%/$OEC_VERSION/g" /oec-deb/DEBIAN/control && \
sed -i "s/%INTEGRATION%/${INTEGRATION,,}/g" /oec-deb/DEBIAN/control && \

cd ~ && \
mkdir -p $OUTPUT/oec-packages-$OEC_VERSION/${INTEGRATION,,} && \

mkdir /deb-package && \
dpkg-deb -b /oec-deb /deb-package && \
cp -R /deb-package/${INTEGRATION,,}* $OUTPUT/oec-packages-$OEC_VERSION/${INTEGRATION,,}/